version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::490195310065:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-T6NSTX6ORSO8"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::490195310065:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1VRW6S49TBKO7"
cloudformation_execution_role = "arn:aws:iam::490195310065:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1S163GV73C44N"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-4leoc9szulx0"
image_repository = ""
region = "ap-southeast-2"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::490195310065:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1UXX1V9VDOUHO"
cloudformation_execution_role = "arn:aws:iam::490195310065:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-TXWZPU0AUSUF"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-h2qg5q7ybmcq"
image_repository = ""
region = "ap-southeast-2"
